//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecuritmentsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_Companies
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int CandidateId { get; set; }
        public bool IsCurrentCompany { get; set; }
        public decimal CTC { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Candidate Candidate1 { get; set; }
        public virtual Company Company { get; set; }
    }
}
