//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecuritmentsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Candidate_Skills = new HashSet<Candidate_Skills>();
            this.Candidate_Companies = new HashSet<Candidate_Companies>();
            this.Candidate_Companies1 = new HashSet<Candidate_Companies>();
        }
    
        public int CandidateId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNumber { get; set; }
        public string EmailId { get; set; }
        public int Experience { get; set; }
        public int NoticePeriod { get; set; }
        public decimal ExpectedCTC { get; set; }
        public string AlternateNumber { get; set; }
        public string AlternateEmail { get; set; }
        public int StatusId { get; set; }
        public int LocationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate_Skills> Candidate_Skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate_Companies> Candidate_Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate_Companies> Candidate_Companies1 { get; set; }
        public virtual Location Location { get; set; }
        public virtual Status Status { get; set; }
    }
}
